-- MySQL Script generated by MySQL Workbench
-- Tue Oct 16 18:43:18 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema egresso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema egresso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `egresso` DEFAULT CHARACTER SET latin1 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cursos` (
  `id` INT NULL,
  `curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ano` (
  `id_ano` INT NOT NULL,
  `ano` DATETIME NOT NULL,
  PRIMARY KEY (`id_ano`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`semestre` (
  `id_semestre` INT NOT NULL,
  `semestre` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_semestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `id_cidade` INT NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`alunos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `RA` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `foto` VARCHAR(60) NULL,
  `cursos_id` INT NOT NULL,
  `ano_id_ano` INT NOT NULL,
  `semestre_id_semestre` INT NOT NULL,
  `cidade_id_cidade` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `RA_UNIQUE` (`RA` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `fk_alunos_cursos`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `mydb`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_ano1`
    FOREIGN KEY (`ano_id_ano`)
    REFERENCES `mydb`.`ano` (`id_ano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_semestre1`
    FOREIGN KEY (`semestre_id_semestre`)
    REFERENCES `mydb`.`semestre` (`id_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alunos_cidade1`
    FOREIGN KEY (`cidade_id_cidade`)
    REFERENCES `mydb`.`cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`frequencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`frequencia` (
  `id_frequencia` INT NOT NULL,
  `RA` INT NOT NULL,
  `data_entrada` DATETIME NOT NULL,
  `data_saida` DATETIME NOT NULL,
  `alunos_id` INT NOT NULL,
  PRIMARY KEY (`id_frequencia`),
  UNIQUE INDEX `id_frequencia_UNIQUE` (`id_frequencia` ASC) VISIBLE,
  UNIQUE INDEX `RA_UNIQUE` (`RA` ASC) VISIBLE,
  CONSTRAINT `fk_frequencia_alunos1`
    FOREIGN KEY (`alunos_id`)
    REFERENCES `mydb`.`alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `egresso` ;

-- -----------------------------------------------------
-- Table `egresso`.`Questionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `egresso`.`Questionario` (
  `id_Perguntas` INT UNSIGNED NOT NULL,
  `motivo_particular` TINYINT(1) NOT NULL,
  `motivo_profissional` ENUM('1', '2', '3') NOT NULL,
  `faculdade_puplica` ENUM('1', '2') NOT NULL,
  `faculdade_particular` ENUM('1', '2') NOT NULL,
  `ingressou_outraescola` ENUM('1', '2') NOT NULL,
  `dificuldade_aprendizagem` ENUM('1', '2', '3') NOT NULL,
  `problemas_saude_pessoal` ENUM('1', '2') NOT NULL,
  `falta_motivacao` ENUM('1', '2') NOT NULL,
  `insatisfacao_curso` ENUM('1', '2', '3') NOT NULL,
  `interesse_curso` ENUM('1', '2', '3') NOT NULL,
  `infraestrutura_faculdade` ENUM('1', '2', '3') NOT NULL,
  `didatica_teorica` ENUM('1', '2', '3') NOT NULL,
  `troca_de_curso_fatec` ENUM('1', '2') NOT NULL,
  `curso_outra_fatec` ENUM('1', '2') NOT NULL,
  `troca_de_turno_fatec` ENUM('1', '2') NOT NULL,
  `n_terminara_noprazo` ENUM('1', '2') NOT NULL,
  `frequencia_id_frequencia` INT NOT NULL,
  PRIMARY KEY (`id_Perguntas`),
  CONSTRAINT `fk_Questionario_frequencia`
    FOREIGN KEY (`frequencia_id_frequencia`)
    REFERENCES `mydb`.`frequencia` (`id_frequencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `egresso`.`area_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `egresso`.`area_curso` (
  `area_curso_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`area_curso_id`),
  UNIQUE INDEX `area_curso_id_UNIQUE` (`area_curso_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
